services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${a}
      POSTGRES_USER: ${b}
      POSTGRES_PASSWORD: ${c}
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  url-shortener-app:
    build: .
    container_name: url-shortener
    environment:
      - SPRING_DATASOURCE_URL=${d}
      - SPRING_DATASOURCE_USERNAME=${b}
      - SPRING_DATASOURCE_PASSWORD=${c}
    ports:
      - "8080:8080"
    depends_on:
      - postgres




volumes:
  pgdata: